services:
  database:
    image: postgres:16.4
    container_name: database
    profiles: [ db, dev ]
    networks:
      - reminders-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reminders_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    tty: true
    cpu_count: 2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  database-migrations:
    image: ghcr.io/emilpriver/geni:v1.1.4
    container_name: database-migrations
    profiles: [ db, dev ]
    networks:
      - reminders-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/reminders_dev
    volumes:
      - ./migrations:/migrations
    command: up

networks:
  reminders-network:


volumes:
  postgres_data:
